version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
  test_db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: $DB_NAME_TEST
      POSTGRES_USER: $DB_USER_TEST
      POSTGRES_PASSWORD: $DB_PASS_TEST
  web:
    build: .
    restart: always
    depends_on:
      - db
      - test_db
    env_file:
      - .env
    ports:
      - 8000:8000
